red-hat-data-services/rhods-operator

Dockerfiles/Dockerfile, Makefile, PROJECT, apis/dscinitialization/v1alpha1/dscinitialization_types.go, bundle/metadata/annotations.yaml, config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml, config/manifests/description-patch.yml, config/manifests/kustomization.yaml, config/rbac/datasciencecluster_datasciencecluster_editor_role.yaml, config/rbac/datasciencecluster_datasciencecluster_viewer_role.yaml, config/rbac/dscinitialization_dscinitialization_editor_role.yaml, config/rbac/dscinitialization_dscinitialization_viewer_role.yaml, config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml, config/samples/dscinitialization_v1alpha1_dscinitialization.yaml, controllers/dscinitialization/dscinitialization_controller.go, docs/Dev-Preview.md, main.go
update namespaces, bundle repo, branches, descriptions in CSV
=> Adapt for RHODS

components/dashboard/dashboard.go
(cherry picked from commit fb72455ee23ce21486b0378da63fb4914fee1642)
=> Add Authentication overlay for dashboard

pkg/plugins/addLabelsplugin.go
(cherry picked from commit 1d6035fbb6a5bb4e5eb943a43a2e0b07957db323)
=> Update label plugin to include selectors

apis/datasciencecluster/v1alpha1/datasciencecluster_types.go, bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml, bundle/manifests/opendatahub-operator.clusterserviceversion.yaml, components/codeflare/codeflare.go, components/dashboard/dashboard.go, components/kserve/kserve.go, components/ray/ray.go, config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml, controllers/datasciencecluster/datasciencecluster_controller.go, controllers/dscinitialization/dscinitialization_controller.go, controllers/status/status.go, go.mod, go.sum, pkg/deploy/deploy.go, pkg/plugins/addLabelsplugin.go
Add ODHDashboardconfig in dasboard component
(cherry picked from commit 2a8757d7fb08c8381082902827c3ce95058e5e47)
Add admin group for downstream
(cherry picked from commit 8a72ab97c49ef1d32c67d7e6b13b72eaa363ac33)
Add ImageParams for kuberay and codeflare
(cherry picked from commit ab2fdab798a73c49844f558d5bdd0eff8afbcfc9)
Add consolelink for new operator only on cloudserver cluster
- Move from util to common for ReplaceStringsInFile
(cherry picked from commit 80c69bb9a31b4421aca505270e148d918b6f252e)
Fix: version number and add description (#388)
(cherry picked from commit 76ee4894f2fd49a0be32e3bd598af501a3b030c1)
Add ImageParams map for KServe
- …
=> Sync with upstream

README.md, bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml, config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml, main.go
(cherry picked from commit 8bd5cde296808fb781ee1c2abef58b9eb90a393c)
=> [rhods-1.31]DSCInit force update instances

README.md, bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml, config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml, main.go
(cherry picked from commit 8bd5cde296808fb781ee1c2abef58b9eb90a393c)
=> DSCInit force update instances

components/dashboard/dashboard.go
cherry-pick  https://github.com/red-hat-data-services/rhods-operator/pull/28
=> Fix: missing "." in consolelink

components/workbenches/workbenches.go, controllers/dscinitialization/dscinitialization_controller.go
(cherry picked from commit 5a48fc9fa961d3cf089d7b7a6ddb47753e4e8bbf)
=> Move creation of notebooks namespace to workbenches

components/codeflare/codeflare.go, components/dashboard/dashboard.go, components/kserve/kserve.go, components/modelmeshserving/modelmeshserving.go, components/ray/ray.go, components/workbenches/workbenches.go
Pruned resource creation further by deploying dependent resources only when enabled.
=> Add pre config only when component is enabled

controllers/dscinitialization/monitoring.go
cherry-pick from https://github.com/red-hat-data-services/rhods-operator/pull/48
=> Fix merge issue

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/datasciencecluster/kubebuilder_rbac.go, controllers/dscinitialization/monitoring.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/550
=> Update: rbac for codeflare role

Makefile, bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml
this is to preprare for 1.35(renamed to 2.4)
=> uplift: set version to 2.4.0

components/trustyai/trustyai.go
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/665
=> fix: wrong trustyai env variable name

components/kserve/kserve.go, get_all_manifests.sh
- dashboard and modelmesh-monitoring still from odh-manifests
=> update(manifests): enable more components

components/modelmeshserving/modelmeshserving.go
cherry-pick from https://github.com/opendatahub-io/opendatahub-operator/pull/639
=> fix(mm): set the new logic for modelmesh

components/workbenches/workbenches.go
Fix Deployment of Kf controller to use a dedicated path for downstream
=> Fix the KF deployment:

controllers/dscinitialization/monitoring.go
(cherry picked from commit 001cad1018c0b07c2be6aa5692a4d0815f2efd6a)
=> fix(monitoring): do the switch for dev mode to not send alert

bundle/manifests/redhat-ods-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/rhods-operator.clusterserviceversion.yaml, components/workbenches/workbenches.go, config/monitoring/base/rhods-servicemonitor.yaml, config/monitoring/blackbox-exporter/base/blackbox-exporter-deployment.yaml, config/monitoring/networkpolicy/applications.yaml, config/monitoring/networkpolicy/kustomization.yaml, config/monitoring/networkpolicy/monitoring.yaml, config/monitoring/networkpolicy/operator.yaml, config/monitoring/prometheus/apps/prometheus-configs.yaml, config/monitoring/prometheus/base/prometheus-deployment.yaml, config/monitoring/prometheus/base/prometheus-service.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/role.yaml, controllers/dscinitialization/monitoring.go, controllers/dscinitialization/utils.go
- remove https:// for dashboard target
- add nwp from odh-deployer with some udpates
- fix: wrong service name for operator, this is defined in CSV
- port: do not use https but 8080 and rename from https to metrics
ref : https://github.com/opendatahub-io/opendatahub-operator/issues/357
=> Update(manifests): for monitoring

Makefile, bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/monitoring/alertmanager/alertmanager-configs.yaml, config/monitoring/alertmanager/alertmanager-service.yaml, config/monitoring/base/rhods-servicemonitor.yaml, config/monitoring/networkpolicy/monitoring/monitoring.yaml, config/monitoring/networkpolicy/operator/operator.yaml, config/monitoring/prometheus/apps/prometheus-configs.yaml, config/rbac/role.yaml, controllers/datasciencecluster/kubebuilder_rbac.go, controllers/dscinitialization/dscinitialization_controller.go, controllers/dscinitialization/utils.go
according to https://github.com/red-hat-data-services/odh-deployer/blob/main/deploy.sh#L113
we need all 3 labels on monitoring, application 2 namespaces.
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/357
related: https://issues.redhat.com/browse/RHODS-7978
=> fix(dsci): missing label on namespaces

controllers/dscinitialization/utils.go
ref:  https://github.com/opendatahub-io/opendatahub-operator/pull/700
=> cherry-pick: networkpolicy

config/monitoring/prometheus/apps/prometheus-configs.yaml
ref: https://issues.redhat.com/browse/RHODS-12812
=> fix typo for namespace in codeflare

bundle/manifests/rhods-operator.clusterserviceversion.yaml, components/modelmeshserving/modelmeshserving.go, config/manifests/bases/rhods-operator.clusterserviceversion.yaml, config/samples/dscinitialization_v1_dscinitialization.yaml, controllers/dscinitialization/dscinitialization_controller.go, controllers/dscinitialization/dscinitialization_test.go, main.go, pkg/upgrade/upgrade.go, tests/e2e/controller_setup_test.go
- rhods => default-dsc
- rhods-setup => default-dsci
part of: https://github.com/opendatahub-io/opendatahub-operator/issues/706
=> Update: instance default name

config/monitoring/base/cluster-monitor-rolebinding.yaml, config/monitoring/base/rhods-servicemonitor.yaml, config/monitoring/segment/segment-key-config.yaml, config/monitoring/segment/segment-key-secret.yaml, controllers/dscinitialization/monitoring.go
- remove hardcoded app. namespace in segment manifests
- remove hardcoded monitoring. namepsace in base manifests
- add placeholder to inject monitoring namespace in Servicemonitor
=> update(monitoring): segment

controllers/dscinitialization/monitoring.go
Prometheus Deployment stuck in `wait-for-deployments`  when couple of components are set to `Removed` 
Reason being the deployment is patched after upgrade and the initContainer stays intact
=> Fix regression in Prometheus Deployment

controllers/dscinitialization/monitoring.go, main.go
=> Remove legacy blackbox exporter

components/kserve/kserve.go, pkg/feature/feature.go, pkg/feature/initializer.go
PR https://github.com/opendatahub-io/opendatahub-operator/pull/744
=> [sync] from ODH for main

components/component.go
ref:  https://issues.redhat.com/browse/RHODS-12867
=> fix(monitoring): cannot load dashbaord record rules

components/modelmeshserving/modelmeshserving.go
after rebase the functions params position changed....
=> fix(rebase): in previous commits

pkg/feature/conditions.go, pkg/feature/templates/serverless/serving-install/knative-serving.tmpl
PR https://github.com/opendatahub-io/opendatahub-operator/pull/762
PR https://github.com/opendatahub-io/opendatahub-operator/pull/761
=> [Sync] upstream incubation to rhods- 2.5

pkg/upgrade/upgrade.go
ref: https://issues.redhat.com/browse/RHOAIENG-115
=> chore: typo

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/samples/datasciencecluster_v1_datasciencecluster.yaml, config/samples/dscinitialization_v1_dscinitialization.yaml, pkg/upgrade/upgrade.go
Ref: https://issues.redhat.com/browse/RHOAIENG-126
=> Update defaults for modelmesh

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/samples/datasciencecluster_v1_datasciencecluster.yaml, config/samples/dscinitialization_v1_dscinitialization.yaml, pkg/upgrade/upgrade.go
Reverts red-hat-data-services/rhods-operator#143
=> Revert "Update defaults for modelmesh"

config/monitoring/prometheus/apps/prometheus-configs.yaml
JIRA : https://issues.redhat.com/browse/RHOAIENG-98
=> add recording and alerting rules for kserve

components/component.go, config/monitoring/prometheus/apps/prometheus-configs.yaml, controllers/dscinitialization/monitoring.go
Add recording and alerting rules for TrustyAI ([RHOAIENG-99](https://issues.redhat.com/browse/RHOAIENG-99)).
Note: SOPs not merged yet.
=> Add recording and alerting rules for TrustyAI

components/kserve/kserve.go
ref: https://issues.redhat.com/browse/RHOAIENG-440
=> fix: wrong name in the message

config/monitoring/prometheus/apps/prometheus-configs.yaml
Signed-off-by: Vedant Mahabaleshwarkar <vmahabal@redhat.com>
(cherry picked from commit 246a361a06c535b81b1ac4fcfb881ed47f3ad9e6)
=> Redefine Kserve Controller Manager scrape config

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/description-patch.yml
https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1548
ref:  https://issues.redhat.com/browse/RHOAIENG-2188
=> [cherrypick]: from midstream to 2.6 for renaming

components/kueue/kueue.go
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/847
=> [cherry-pick]: upstream change for var name

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/datasciencecluster/datasciencecluster_controller.go, controllers/datasciencecluster/kubebuilder_rbac.go, controllers/dscinitialization/dscinitialization_controller.go, controllers/dscinitialization/suite_test.go, main.go, pkg/deploy/deploy.go, pkg/upgrade/upgrade.go, tests/e2e/dsc_cfmap_deletion_test.go
ref: 
RHOAIENG-499 / RHOAIENG-1452
RHOAIENG-2479
=> sync: from upstream to 2.7

config/monitoring/prometheus/apps/prometheus-configs.yaml
* update(trustyai): adding logic to monitoring
* fix(trustyai): prometheus rules for probe
* update(trusty): prometheus to use job instead of instance name for record rules
---------
=> [backport] from 2.6 to main (#173)

components/kserve/kserve.go
(cherry picked from commit 2356d5430b716cb5d20f82e4ca2f31c79bcec70f)
=> Fix Manual Installation of Kserve

controllers/datasciencecluster/datasciencecluster_controller.go
Additional changes for https://issues.redhat.com/browse/RHOAIENG-3391
=> Set TrustyAI status to false

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml
ref: https://issues.redhat.com/browse/RHOAIENG-2044
these are annotations only stated in ocp 4.14
https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html
this will require changes in midstream as well.
since this is a more rhoai related request, it can be done by a backport once we verify CVP is working with tests.
=> update(CSV): more annotation for features.

components/dashboard/dashboard.go
ref: https://issues.redhat.com/browse/RHOAIENG-4159
upstream: https://github.com/opendatahub-io/opendatahub-operator/pull/893
live build: quay.io/wenzhou/rhods-operator-catalog:v2.8.4159
=> [cherrypick]: change for getting odhdashboardconfig with new struct in

components/datasciencepipelines/datasciencepipelines.go
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/891
jira: https://issues.redhat.com/browse/RHOAIENG-4223
=> [cherry-pick]: dspv2 update manifests path for new overlay struct (#891)

config/monitoring/prometheus/apps/prometheus-configs.yaml
Please refer to the ongoing JIRA: https://issues.redhat.com/browse/MTSRE-1822
=> Altering alert from 0.99950 to 0.98

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml
to follow up discussion https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1712673912685679?thread_ts=1712136020.868139&cid=C05NXTEHLGY
ref https://issues.redhat.com/browse/RHOAIENG-5088
this PR has 2 parts:
-  when we added annotation it was not backport to main branch
-  set to false, (see jira issue)
=> update(CSV): annontation for features

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/samples/datasciencecluster_v1_datasciencecluster.yaml, pkg/upgrade/upgrade.go, tests/e2e/helper_test.go
This reverts commit 0854adf92d55a10fbf641c5cd7085a98dc9b24cc.
to set 3DW components to GA ready
=> Revert "Revert "feat(DW): prepare CF,ray,kueue for GA (#929)""

controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
(cherry picked from commit e2aa211971a42a75681acccc720ec5a39803050f)
=> Add watch to deleted ns

config/monitoring/prometheus/apps/prometheus-configs.yaml
depends on: https://github.com/red-hat-data-services/kueue/pull/3
ref: https://issues.redhat.com/browse/RHOAIENG-6819
=> add basic alerting for Kueue

config/monitoring/prometheus/apps/prometheus-configs.yaml
ref:   https://issues.redhat.com/browse/RHOAIENG-6819
https://github.com/red-hat-data-services/rhods-operator/pull/258
=> [sync]: add basic alerting for Kueue (#258)

pkg/cluster/const.go
Jira Issue : https://issues.redhat.com/browse/RHOAIENG-7508
(cherry picked from commit 0ed8f48db0ec27b29391366b6566651922cce2e0)
=> [rhoai-2.10] Fix CSV name for RHOAI

pkg/cluster/const.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-7508 
(cherry picked from commit 0ed8f48db0ec27b29391366b6566651922cce2e0)
=> Fix CSV name for RHOAI

config/monitoring/prometheus/apps/prometheus-configs.yaml
Relates to issue: [RHOAIENG-6431](https://issues.redhat.com/browse/RHOAIENG-6431)
Must merge SOP MR first -> https://gitlab.cee.redhat.com/service/managed-tenants-sops/-/merge_requests/100
=> Added KFTO alerting rule

config/monitoring/prometheus/apps/prometheus-configs.yaml
Updating the KFTO Prometheus config to watch the pod over metrics service.
Relates to [RHOAIENG-6431](https://issues.redhat.com/browse/RHOAIENG-6431)
=> Updated KFTO job to use pod over metric service

components/dashboard/dashboard.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-2883
(cherry picked from commit 3038bffb9908bcb8bf8db22a689a8d14f63b49fe)
=> feat: remove modelserving from dashboard manifests (#1029)

main.go, pkg/upgrade/upgrade.go
cherrypick: https://github.com/opendatahub-io/opendatahub-operator/pull/989
ref: https://issues.redhat.com/browse/RHOAIENG-6571
=> cherry-pick: ODH PR 989 -- remove cleanup for upgrade from v1 to v2

components/kserve/servicemesh_setup.go
sync problem to bring down the logic in ODH which is not needed for RHOAI
ref: https://redhat-internal.slack.com/archives/C070J2ND716/p1719215810364469
=> fix: we should no have this logic in RHOAI

controllers/datasciencecluster/datasciencecluster_controller.go
(cherry picked from commit 70332d85e2b1a96f88caaadb3c0cff435cc7ad7d)
=> fix: add odh-modle-controller NWP to whitelist (#1087)

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/RHOAIENG-9448
=> fix: default serving cert type in initialization-resource for csv

controllers/datasciencecluster/datasciencecluster_controller.go
https://issues.redhat.com/browse/RHOAIENG-9426
=> [backport] fix: add odh-model-controller NWP to whitelist

pkg/cluster/resources.go
upstream fix: https://github.com/opendatahub-io/opendatahub-operator/pull/1116
https://issues.redhat.com/browse/RHOAIENG-9753
=> sync: fix for managed cluster upgrade with DSC already exists

components/dashboard/dashboard.go, get_all_manifests.sh, pkg/deploy/deploy.go
partially cherrypick https://github.com/opendatahub-io/opendatahub-operator/pull/1065
to keep other part not included, which will be done in "sync" PR
ref: https://issues.redhat.com/browse/RHOAIENG-8510
=> cherry-pick: refactor dashboard manifests

components/kserve/kserve.go, components/kserve/kserve_config_handler.go
This reverts commit 55320b6606d26046beaffd91132f54ecf1762e97.
https://issues.redhat.com/browse/RHOAIENG-9664
=> Revert "chore(cleanup): remove checkDependentOperators as duplicated logic (#996)" (#1107)

controllers/dscinitialization/dscinitialization_controller.go
- after remove servicemesh and update condition, instance has been updated
- use retryonconflict to make sure it is removed when something else might also update DSCI at the same time
https://issues.redhat.com/browse/RHOAIENG-9606
=> [sync] fix: when delete DSCI CR get current instance and remove finalizer on it

pkg/cluster/cluster_config.go
original PR: https://github.com/opendatahub-io/opendatahub-operator/pull/1146/files
detail offline discussion: https://redhat-internal.slack.com/archives/C0797MV7J20/p1722354852546469?thread_ts=1722351838.529169&cid=C0797MV7J20
https://issues.redhat.com/browse/RHOAIENG-10678
=> [sync] fix: for Managed cluster, to correct Catsrc namespace

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml
from odh https://github.com/opendatahub-io/opendatahub-operator/pull/1138
=> [sync] chore: update min k8s version to match min ocp version: 1.25 for 4.12

.gitignore, CONTRIBUTING.md, Dockerfiles/Dockerfile, Makefile, bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manager/manager.yaml, get_all_manifests.sh, pkg/deploy/deploy.go
- from odh-manifests to opt/manifests
- set default manifests path in CSV
- user can point to local manifests for debug
https://github.com/opendatahub-io/opendatahub-operator/pull/1143 ( https://github.com/opendatahub-io/opendatahub-operator/commit/5b7da9834f8cf5ce49609b6fbb0ecc6d5b329380)
- bring [705d980](https://github.com/red-hat-data-services/rhods-operator/commit/705d980f2dd729d801a61087716e0c0da587adc7) ("chore: keeps repositories in the tmp dir (https://github.com/opendatahub-io/opendatahub-operator/pull/774)")
local build: quay.io/wenzhou/rhods-operator:2.12.311
=> [sync] chore: change local "manifests" folder to match in-image path (#1143)

pkg/deploy/deploy.go, pkg/plugins/removerplugin.go, tests/e2e/dsc_creation_test.go
sync from ODH https://github.com/opendatahub-io/opendatahub-operator/pull/1147
commit https://github.com/opendatahub-io/opendatahub-operator/commit/8d5b7a485fd4d4394aa948574a7e57e1e13e817e
=> [sync] chore: rename variable/function name

components/dashboard/dashboard.go
- priority for image: when set devFlag: devFlag > imageParam when ot set devFlag: imageParam > default value during operator build time
- prioirty for url, title, groups: regardless set devFlags or not, always determinate by Platform value
upstream commits https://github.com/opendatahub-io/opendatahub-operator/commit/00af70889c858f4d9f53ae3c906af1d66fbcddf9 
https://issues.redhat.com/browse/RHOAIENG-10276
=> [sync] fix: devFlags for dashboard did not set correct values (#1136)

pkg/cluster/resources.go
(cherry picked from commit ca3c6e24946faf782fcc779e0013fc118b1d8b94)
https://issues.redhat.com/browse/RHOAIENG-11135
=> sync: fix for managed cluster upgrade with DSC already exists (#305)

.github/workflows/linter.yaml, .golangci.yml, Makefile, README.md, controllers/dscinitialization/suite_test.go, crd-ref-docs.config.yaml, docs/DESIGN.md, docs/api-overview.md, docs/troubleshooting.md, docs/upgrade-testing.md, get_all_manifests.sh, main.go, tests/e2e/dsc_creation_test.go
mostly for the chore and test/ci related changes
=> [sync]: from ODH to downstream

controllers/dscinitialization/dscinitialization_controller.go
- the same code has been called up in the Reconcile()
- for both DSCI status and appl. namespace creation
(cherry picked from commit 1a8ce2c81aa20a8f6632320947858d1ec4c3b8c7)
part of https://issues.redhat.com/browse/RHOAIENG-11883
=> [sync] chore: remove dead code (#1203)

controllers/datasciencecluster/datasciencecluster_controller.go, pkg/deploy/deploy.go
* update: logic for manage resource with skip unnecessary reconcile
- add predicate.Funcs for deployments to reduce reconciles on all components
---------
(cherry picked from commit 6f82d018007562ab5393ed88cb2a951b865bc719)
=> [sync] feat: add predicates on deployment (#1172)

Makefile, README.md, components/codeflare/codeflare.go, components/component.go, components/dashboard/dashboard.go, components/datasciencepipelines/datasciencepipelines.go, components/kserve/kserve.go, components/kserve/kserve_config_handler.go, components/kserve/servicemesh_setup.go, components/kueue/kueue.go, components/modelmeshserving/modelmeshserving.go, components/ray/ray.go, components/trainingoperator/trainingoperator.go, components/trustyai/trustyai.go, components/workbenches/workbenches.go, controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go, main.go, pkg/cluster/cluster_config.go, pkg/cluster/resources.go, pkg/common/common.go, pkg/deploy/deploy.go, pkg/logger/logger.go, pkg/upgrade/uninstallation.go, pkg/upgrade/upgrade.go, tests/e2e/controller_setup_test.go, tests/e2e/dsc_creation_test.go, tests/integration/features/features_suite_int_test.go, tests/integration/features/resources_int_test.go
https://github.com/opendatahub-io/opendatahub-operator/pull/1201
https://github.com/opendatahub-io/opendatahub-operator/pull/998
https://issues.redhat.com/browse/RHOAIENG-349
=> [sync]: "fix: add check for all platform offering on components" + "loggers"

components/workbenches/workbenches.go
ref: https://issues.redhat.com/browse/RHOAIENG-12409
this is a partily cherry-pick from original PR https://github.com/red-hat-data-services/rhods-operator/pull/343 to limit the change only for mentioned bug
=> fix: do not apply resource till applyparams() calls

docs/DESIGN.md, docs/upgrade-testing.md, tests/e2e/cfmap_deletion_test.go, tests/e2e/controller_test.go, tests/e2e/creation_test.go, tests/e2e/deletion_test.go, tests/e2e/helper_test.go, tests/e2e/odh_manager_test.go
cherrypick: 
https://github.com/opendatahub-io/opendatahub-operator/commit/a611427b6dfba2a2652de18af7b2a8a74db78173
https://github.com/opendatahub-io/opendatahub-operator/commit/fc005e3c201ed29e15afdf4dd9640f09b9f2fede
https://github.com/opendatahub-io/opendatahub-operator/commit/d57bb12e5c01b193fad58b3704045e1c48d8f98e
https://github.com/opendatahub-io/opendatahub-operator/commit/199f08f52372b8a4ef6d9047f9783d9e209855c1
=> [Sync]: test updates from odh to rhoai main

config/monitoring/networkpolicy/operator/operator.yaml
- this was blocked perviously by networkpolicy so user has to be do this by CLI
We have a difference between ODH and RHOAI, that users can login Operator Pod to check in ODH but not in RHOAI.
I first thought it was done purposely by production but when i encountered https://docs.openshift.com/container-platform/4.16/web_console/web_terminal/troubleshooting-web-terminal.html, i realize the problem is NWP blocked connection from 2 mentioned namespace.
https://issues.redhat.com/browse/RHOAIENG-10656
local build: quay.io/wenzhou/rhods-operator-catalog:v2.12.730
install this build and tried to use Web Terminal
before
after
=> fix: allow admin to login to operator pod from OCM Web Terminal

main.go
(cherry picked from commit 8574d6a70cc14b7a1b302af0304b6055b57e1c5f)
https://issues.redhat.com/browse/RHOAIENG-13661
=> [sync]fix: add downstream operator namespace into cache for secret (#1267)

pkg/upgrade/upgrade.go
- seems duplicate to create a new function but mainly:
- can  have a different value for the version
- if we want to keep one and remove another just comment out function
- probably we will have some other with similar logic later till it can be done in UI logic
(cherry picked from commit 1a441e7cb790a220d5d1785ea81259fcff92661c)
https://issues.redhat.com/browse/RHOAIENG-13604
=> [sync] feat: add support for upgrade to force disableModelRegistry to false

OWNERS_ALIASES
Sync of this PR in opendatahub operator
https://github.com/opendatahub-io/opendatahub-operator/pull/1273
=> [sync] fix: fixed typo for jackdelahunt owner

controllers/datasciencecluster/datasciencecluster_controller.go, controllers/dscinitialization/dscinitialization_controller.go
- DSCI: if current version is not matching, update it
- DSC: in both reconcile pass and fail case, update it
(cherry picked from commit 59cade99e5cd1e4d6fd2e1273f71cf2f1597e076)
https://github.com/opendatahub-io/opendatahub-operator/pull/1287
https://issues.redhat.com/browse/RHOAIENG-14187
=> [sync]fix: update release version in DSCI and DSC .status for upgrade case

controllers/datasciencecluster/datasciencecluster_controller.go, controllers/dscinitialization/dscinitialization_controller.go
sync https://github.com/opendatahub-io/opendatahub-operator/pull/1287
https://issues.redhat.com/browse/RHOAIENG-14187
local build: quay.io/wenzhou/rhods-operator-catalog:v2.14.14187
=> [sync]fix: add release status to upgrade case

.github/renovate.json, Dockerfiles/Dockerfile.konflux
=> adding renovate.json and fixing syntax error with Dockerfile.konflux

Makefile, bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/rhods-operator.clusterserviceversion.yaml, config/manifests/description-patch.yml
- update version  to 2.15.0
- user `REPLACE_IMAGE:latest` for  containerImage, that should be replaced by automation later
- change `CPU` back to old value which is being used for production
- we will need to revisit values set there but not done any perf test
- did not add "subs" here
related to https://github.com/red-hat-data-services/rhods-operator/pull/374
=> update: CSV parts missing in downstream for rhoai 2.15

apis/dscinitialization/v1/dscinitialization_types.go, apis/infrastructure/v1/servicemesh_types.go, bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml, docs/api-overview.md
https://github.com/opendatahub-io/opendatahub-operator/pull/1261
https://github.com/opendatahub-io/opendatahub-operator/pull/1263
=> [Sync]: ODH to RHOAI 2.15: validation on namespace

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/crd/external/config.openshift.io_authentications.yaml, config/rbac/role.yaml, controllers/dscinitialization/dscinitialization_controller.go, controllers/dscinitialization/dscinitialization_test.go, controllers/dscinitialization/suite_test.go, pkg/cluster/cluster_config.go, pkg/cluster/const.go
- manual cherry-pick from https://github.com/opendatahub-io/opendatahub-operator/pull/1297
(cherry picked from commit 5bed92113b7fe6f6b7df8236609d5fdf4b84b574)
https://issues.redhat.com/browse/RHOAIENG-14214
=> [sync]:feat: Operator disable create usergroup if detect user enabl external auth

.github/workflows/trigger-nightly-operator-build.yaml
=> adding nightly trigger changes

.github/workflows/bundle-sync.yml
=> disabling dockerfile sync for bundle

config/manager/kustomization.yaml.in
restoring the file with correct upstream content - https://github.com/opendatahub-io/opendatahub-operator/blob/b6124ef88d1937688621756ecacc4404f19a378c/config/manager/kustomization.yaml.in
=> restoring the file with correct upstream content

build/manifests-config.yaml
=> syncing manifests config

Dockerfiles/Dockerfile.konflux
as part of https://issues.redhat.com/browse/RHOAISTRAT-414
=> fix: dockerfile for konflux build

controllers/dscinitialization/monitoring.go, main.go, pkg/cluster/const.go
https://issues.redhat.com/browse/RHOAIENG-18607
https://issues.redhat.com/browse/RHOAIENG-18425
[RHOAIENG-14787](https://issues.redhat.com/browse/RHOAIENG-14787)
=> [Sync] fix from main branch fro 2.17

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/datasciencecluster/kubebuilder_rbac.go
- add update on all cases
(cherry picked from commit ba6df6595fa70342595c43ee202bacc11e8f87f0)
(cherry picked from commit 1feefd3fc04b3be15b49400d5239277cd3a0cd0b)
https://issues.redhat.com/browse/RHOAIENG-18859
=>  [sync]fix: missing update permission on dashboard object (#1579)

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/datasciencecluster/kubebuilder_rbac.go
(cherry picked from commit 6e134b11c495cfae354c70f2afff026e6f295e53)
https://issues.redhat.com/browse/RHOAIENG-18913
=> [sync]fix: missing permission to update prometheusrules (#1581)

bundle/manifests/rhods-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/datasciencecluster/kubebuilder_rbac.go
- cleanup duplicated one
(cherry picked from commit 64fefca0122ecea0f3cf1456d85aebfa0c744b94)
(cherry picked from commit 5d47007deada2071f8f8a0445db5ff5c8d76e25b)
https://issues.redhat.com/browse/RHOAIENG-18859
=> [sync] fix: more permission need for dashboard for consolelink (#1587)

.tekton/odh-operator-v2-18-scheduled.yaml
=> updating coverity-availability

Dockerfiles/Dockerfile.konflux
sync changes from https://github.com/opendatahub-io/opendatahub-operator/pull/1630
=> feat: enable konflux to build fips and multi-arch image

Dockerfiles/Dockerfile.konflux, go.mod, go.sum
- base ubi image to the latest one (built 18hr ago)
- forec replace glog to the latest version (released days ago) we do not directly use glog but imported from grpc
ref https://issues.redhat.com/browse/RHOAIENG-21707
=> update: glog to 1.2.4 + base ubi image

.tekton/odh-operator-v2-20-push.yaml
=> trigger ci

controllers/components/kserve/kserve_support.go
https://issues.redhat.com/browse/RHOAIENG-22090
=> fix: need wildcard for ingress

.tekton/odh-operator-v2-19-push.yaml, .tekton/odh-operator-v2-19-scheduled.yaml
required to pass conforma after 1 april
=> [KONFLUX-2264,RHOAIENG-22379] add sast tasks to konflux

controllers/components/kserve/kserve_controller_actions.go
https://issues.redhat.com/browse/RHOAIENG-22518
local build quay.io/wenzhou/rhods-operator-catalog:v2.19.22518
=> fix: add error on no CRD found from serverless servicemesh

.tekton/odh-operator-v2-20-push.yaml
=> [KONFLUX-2264,RHOAIENG-22432] add sast tasks to konflux

Dockerfiles/Dockerfile.konflux
Jira: https://issues.redhat.com/browse/RHOAIENG-23629
=> Update Dockerfile.konflux to use go-1.23 builder

controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml, controllers/services/auth/resources/admingroup-role.tmpl.yaml
we have RBAC added in Auth in ODH but seems not sync correctly to RHOAI 2.19 and 2.20
backport this fix, which wont include https://github.com/opendatahub-io/opendatahub-operator/pull/1839
https://github.com/opendatahub-io/opendatahub-operator/pull/1508/
https://github.com/opendatahub-io/opendatahub-operator/pull/1512
https://github.com/opendatahub-io/opendatahub-operator/pull/1538
ref: https://issues.redhat.com/browse/RHOAIENG-26098
=> [backport]: missing permissions for dashboard to get user/groups

build/manifests-config.yaml
Follow up PR for https://github.com/red-hat-data-services/rhods-operator/pull/8611
=> fix: use branch sync

build/manifests-config.yaml
Resetting Manifest Config to test llama-stack-k8s-operator config
=> reset manifest-config.yaml

api/services/v1alpha1/monitoring_types.go, bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml, bundle/manifests/rhods-operator.clusterserviceversion.yaml, bundle/manifests/services.platform.opendatahub.io_monitorings.yaml, config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml, config/crd/bases/services.platform.opendatahub.io_monitorings.yaml, config/rbac/role.yaml, docs/api-overview.md, internal/controller/dscinitialization/kubebuilder_rbac.go, internal/controller/services/monitoring/monitoring_controller.go, internal/controller/services/monitoring/monitoring_controller_actions.go, internal/controller/services/monitoring/monitoring_controller_support.go, internal/controller/services/monitoring/resources/instrumentation.tmpl.yaml, internal/controller/status/status.go, pkg/cluster/gvk/gvk.go, tests/e2e/creation_test.go, tests/e2e/helper_test.go, tests/e2e/monitoring_test.go
* RHOAIENG-25583 | feat: Added otel auto-instrumentation
* fix: added new line to monitoring_test.go to fix linter issue
* update: regenerate manifests from latest source code
* remove unneccessary function
* RHOAIENG-25538 | test: Adding removed tests
* monitoring e2e test code optimization
---------
(cherry picked from commit 4341169f7bbea411baa6263727b89236ab396bb6)
=> [SYNC] RHOAIENG-25583 feat: Added otel auto-instrumentation (#2218)

Dockerfiles/Dockerfile.konflux
fix https://issues.redhat.com/browse/RHOAIENG-30181
=> fix: konflux special build

.tekton/odh-operator-v2-22-push.yaml
=> onboard rhoai-2.22.1

Dockerfiles/Dockerfile.konflux
ref https://issues.redhat.com/browse/RHOAIENG-29974
=> uplift: konflux build use new Go 1.24 image

Dockerfiles/Dockerfile.konflux
=> Fix Konflux dockerfile

config/monitoring/base/rhods-servicemonitor.yaml
(cherry picked from commit eb367faf008bbefb0259df460bb379a4e595fe0c)
ref: https://issues.redhat.com/browse/RHOAIENG-32923
=>  [sync] revert changes to federation servicemonitor (#2357)

internal/controller/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
=> [CHERRY-PICK] RHOAIENG-26313-enable-multi-container-probing

Dockerfiles/Dockerfile.konflux
Fix for security vulnerability issue: https://issues.redhat.com/browse/RHOAIENG-24687
=> Use go-toolset 1.24 builder image

Dockerfiles/Dockerfile.konflux, rpms.in.yaml, rpms.lock.yaml, ubi.repo
This is to match the Dockerfile change made here:
https://github.com/opendatahub-io/opendatahub-operator/pull/2427
=> Add tar to Dockerfile.konflux

Dockerfiles/Dockerfile, Dockerfiles/Dockerfile.konflux
related change from https://github.com/opendatahub-io/opendatahub-operator/pull/2570
**DO NOT MERGE TILL https://github.com/opendatahub-io/opendatahub-operator/pull/2570 Is brought down here (rhoai-2.25)**
=> update: remove kube-config related resource which is not needed

.github/workflows/release-staging.yaml
=> Wznoinsk rhoai 2.25 fix merge conflict

.github/workflows/bundle-sync.yml, .github/workflows/operator-insta-merge.yaml, .github/workflows/operator-processor.yaml
Ref: https://redhat-internal.slack.com/archives/C07ANR2U56C/p1759487924595049?thread_ts=1759454700.043519&cid=C07ANR2U56C
=> fix glob pattern for matching rhoai release branches
