red-hat-data-services/rhods-operator

bundle/manifests/redhat-ods-operator-metrics-service_v1_service.yaml
bundle/manifests/redhat-ods-operator_v1_configmap.yaml
bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_client_clusterrole.yaml
config/rbac/auth_proxy_service.yaml
docs/Dev-Preview.md

replace old lable "control-plane: controller-manager" to "app.kubernetes.io/part-of: rhods-ods-operator" as most of rhods components have done this change.

Rename prefix and set clear label on resource

---

components/dashboard/dashboard.go

cherry-pick : https://github.com/opendatahub-io/opendatahub-operator/pull/420
from test:
wrong link:
https://rhods-dashboard-redhat-ods-applicationsapps.ods-qe-01.rhods.ccitredhat.com/
should be:
https://rhods-dashboard-redhat-ods-applications.apps.ods-qe-01.rhods.ccitredhat.com/
Ref: https://github.com/opendatahub-io/opendatahub-operator/issues/261

Fix: missing "." in consolelink

---

pkg/plugins/namespacePlugin.go

Namespace plugin config is overwritten by namespace defined by the [ kustomization.yaml](https://github.com/red-hat-data-services/odh-manifests/blob/master/kserve/base/kustomization.yaml#L6) when the plugin is not explicitly updated to include namespace references into Plugin [config](https://github.com/red-hat-data-services/rhods-operator/blob/feature-rearchitecture/pkg/plugins/namespacePlugin.go)
Add all required references to namespace plugin.

Update Namespace plugin for Kserve configs

---

components/kserve/kserve.go
main.go

we should finally apply manifests with replaced image
the old logic is:
- apply `"kserve"` manifests
- replace `odh-model-controller` image value in `kserve` folder
- apply `odh-model-controller` manifests
- 
If we have `modelmeshserving` component first enabled and reconciled, it will get correct image of `odh-model-controller` in `odh-model-controller` folder, 
but if we create DSC instance directly with `Remove on modelmeshserving `+ `Managed on kserve`, it will not update content of `odh-model-controller/base/params.env`, 
thus, above logic will still use quay.io image of odh-modelmesh-controller.
fix: https://issues.redhat.com/browse/RHODS-11613

Fix: wrong path for the image update + wrong API version

---

bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
controllers/dscinitialization/monitoring.go

- reapply [PR #34](https://github.com/red-hat-data-services/rhods-operator/pull/34)
- seems when we apply sync from ODH with big API change, mistakenly reverted this fix for "segment-io" [bug](https://github.com/opendatahub-io/opendatahub-operator/issues/445)
- csv change is only after re-generate it

Fix merge issue

---

components/kserve/kserve.go

ref: https://issues.redhat.com/browse/RHODS-12074

Fix: odh-model-controller images are not using digest instead they are using tag for RHODS 1.33 v2

---

.github/workflows/linter.yaml
README.md
bundle/manifests/rhods-operator.clusterserviceversion.yaml
components/codeflare/codeflare.go
components/modelmeshserving/modelmeshserving.go
components/ray/ray.go
components/workbenches/workbenches.go
config/manifests/bases/rhods-operator.clusterserviceversion.yaml
config/samples/datasciencecluster_v1_datasciencecluster.yaml
config/samples/dscinitialization_v1_dscinitialization.yaml
controllers/dscinitialization/dscinitialization_controller.go
controllers/dscinitialization/dscinitialization_test.go
controllers/dscinitialization/monitoring.go
get_all_manifests.sh
main.go
pkg/upgrade/upgrade.go
tests/e2e/controller_setup_test.go

- update path to use rhods org not odh org
- enable notebook, dw, dsp, set to use main/master
- fix some lint
- disable unit-test till we can fix the failure first. this is done in the GH not in code.
- revert logic updated in "modelmesh" till manifests is ready to use, still need point to rhods odh-manifests but keep checking new DSCI on  name  => this can fix the current "main" with reconciles.
- fix wrong syntax in CSV causing operator cannot be installed
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/579
quay.io/wenzhou/opendatahub-operator-catalog:v2.10.21-3

update(manifests): update dsp, notebook + fix errors

---

components/codeflare/codeflare.go
components/component.go
components/dashboard/dashboard.go
components/datasciencepipelines/datasciencepipelines.go
components/kserve/kserve.go
components/ray/ray.go
components/trustyai/trustyai.go
components/workbenches/workbenches.go
get_all_manifests.sh
main.go
pkg/common/common.go
pkg/deploy/deploy.go
pkg/deploy/setup.go
pkg/upgrade/upgrade.go

- fix wrong path for nbc
- fix missing https://github.com/opendatahub-io/opendatahub-operator/pull/649
- enable notebook to use get_manifests
- update get_manifests to use rhods-2.4 branch
- fix lint
- cleanup code
- sync changes from ODH
- fix wrong applyimage for codeflare
- remove duplicated code
test image:
quay.io/wenzhou/opendatahub-operator-catalog:v2.10.579-30

fix: a brunch of changes for 2.4

---

components/workbenches/workbenches.go

ref https://github.com/opendatahub-io/opendatahub-operator/pull/663
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/579
ref: https://github.com/red-hat-data-services/kubeflow/pull/29

update: workbench images into 2 params.env files

---

bundle/manifests/redhat-ods-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/rhods-operator.clusterserviceversion.yaml
components/component.go
config/manager/manager.yaml
config/monitoring/base/rhods-servicemonitor.yaml
config/monitoring/networkpolicy/applications/applications.yaml
config/monitoring/prometheus/apps/prometheus-configs.yaml
config/monitoring/prometheus/base/prometheus-service.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/role.yaml
controllers/datasciencecluster/kubebuilder_rbac.go

- add port in operator deployment which is used by SVC
- add alerts for operator: when both UI and workbench disable == 0
- fix wrong metric name...
- add default networkpolicy for RHODS too
- add missing permission
live-builder:  quay.io/wenzhou/opendatahub-operator-catalog:v2.10.28-2
fix: https://issues.redhat.com/browse/RHODS-4050

update: monitoring

---

Makefile
components/component.go
config/monitoring/base/rhods-prometheusrules.yaml
config/monitoring/base/rhods-servicemonitor.yaml
config/monitoring/networkpolicy/monitoring/monitoring.yaml
config/monitoring/networkpolicy/operator/operator.yaml
config/monitoring/prometheus/apps/prometheus-configs.yaml
controllers/dscinitialization/monitoring.go
controllers/dscinitialization/utils.go

- add log in pod for QE to see it is dev mode cluster 
- add two metrics: i do not think they are used in this config but they are presented in v1 config , so i add back
ref: ref: https://issues.redhat.com/browse/RHODS-12867
live build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.11.9-13
matches
fixed duplicated dashboard alerts
local build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.11.9-0

update(monitoring): metrics

---

config/monitoring/base/cluster-monitor-rolebinding.yaml
config/monitoring/base/rhods-prometheusrules.yaml
config/monitoring/base/rhods-servicemonitor.yaml
controllers/dscinitialization/monitoring.go
pkg/plugins/namespacePlugin.go

- this is the reason why our rolebinding it set to `openshift-monitorig` but got replaced with our `monitoring namespace` which causes monitoring not working
- to not cause any side effect: will keep plugin as-is for this release,
- only to hardcoded our monitoring namespace in monitoring/base folder manifests
P.S:  seems only with removing plugin part is not helping, might need to check `SetRoleBindingSubjects: namespace.AllServiceAccountSubjects,` later
ref: https://issues.redhat.com/browse/RHODS-12867

fix(monitoring): do not set odh monitoring namespace when apply for  manifests in "monitoring/base"

---

pkg/plugins/addLabelsplugin.go

see https://github.com/opendatahub-io/opendatahub-operator/pull/631
part I: https://github.com/opendatahub-io/opendatahub-operator/issues/746
this is gonna make v2.2->v2.4 back to work

revert: label changes made in upgrade PR

---

config/monitoring/prometheus/apps/prometheus-configs.yaml
controllers/dscinitialization/monitoring.go

- match does not work with * in the string need to use (.*)
ref:  https://issues.redhat.com/browse/RHODS-12867
report by https://redhat-internal.slack.com/archives/C064Z5S84F3/p1700382245612159
live-build to test: quay.io/wenzhou/opendatahub-operator-catalog:v2.11.19
test:
- install operator
- default GA components all up and prometheus has them in the config
-
- delete DSC
- wait about 2 mins
- check prometheus config again, only find 2 default rules
-

fix(monitoring): when DSC is removed entry in rule_files should be cleanup without panic

---

controllers/datasciencecluster/datasciencecluster_controller.go
main.go
pkg/upgrade/upgrade.go

live build: [quay.io/wenzhou/rhods-operator-catalog:v2.4.0](http://quay.io/wenzhou/rhods-operator-catalog:v2.4.0) 
including rhods 1.33 v1 as FROM in this build
- include edson's rhods-12939 from odh
- fix the logic of adding deployment into markdeletionlist
- add the missing steps in the backoff call=> this is the tricky one, blame bad documentation 
-  ^ creds from @bartoszmajsak
- add cleanup for the monitoring NS for the modelmesh monitoring deployment
-  fix reconcile when we have deletion CM but no error return from operatorunistall

fix: upgrade from v1 to v2

---

controllers/datasciencecluster/datasciencecluster_controller.go

RHODS-12956 : the operator was updating the DSC CR from within the reconciliation loop code, causing an infinite loop.
This fix was discussed with James.
Manually tested in dev cluster

RHODS-12956: removing CR update from the reconciliation loop to avoid infinite loop

---

components/codeflare/codeflare.go
components/dashboard/dashboard.go
components/datasciencepipelines/datasciencepipelines.go
components/modelmeshserving/modelmeshserving.go
components/ray/ray.go
components/workbenches/workbenches.go

this will reduced necessary updates on prometheus configmap
live build: quay.io/wenzhou/rhods-operator:dev-2.5.12966

fix(monitoring): only set prometheus as part-of label from component

---

README.md
bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
config/manifests/bases/rhods-operator.clusterserviceversion.yaml
config/samples/datasciencecluster_v1_datasciencecluster.yaml
controllers/dscinitialization/dscinitialization_controller.go
docs/DESIGN.md
docs/Dev-Preview.md
infrastructure/v1/serverless_types.go
infrastructure/v1/servicemesh_types.go
pkg/cluster/operations.go
pkg/upgrade/upgrade.go

- set OSSM and serving both as default Managaed
- set kserver as default Managed too
- keep modelmesh for new installation as Removed but if it is upgrade from old verison, keep it as-was
- sync fix upstream issue 755 
**live build** quay.io/wenzhou/rhods-operator-catalog:v2.5.1
**test:**
installed 2 dependent operators 
install rhods operator
DSCI created, DSC created, 4 FT created
kserve is managed, modelmesh is removed

update: set kserve as Managed by default DSC + fix nilpointer

---

components/README.md
components/codeflare/codeflare.go
components/component.go
components/dashboard/dashboard.go
components/datasciencepipelines/datasciencepipelines.go
components/kserve/kserve.go
components/modelmeshserving/modelmeshserving.go
components/ray/ray.go
components/trustyai/trustyai.go
components/workbenches/workbenches.go
controllers/datasciencecluster/datasciencecluster_controller.go
pkg/monitoring/monitoring.go

live build quay.io/wenzhou/rhods-operator-catalog:v2.5.12958
we only have dashboard, workbench, codeflare, ray and modelmesh with monitoring enabled. 
ref: https://issues.redhat.com/browse/RHOAIENG-87

fix(monitoring): do not add component rules till service is up

---

components/component.go
components/dashboard/dashboard.go
controllers/secretgenerator/secretgenerator_controller.go
pkg/upgrade/upgrade.go

do force OAuthClient deletion along with secret deletion
update owner to rhods-operator
update APIVersion for the patch, this is to fix error when we only want to patch OAuthClient from secrectgenerator_contorller:
ERROR	Reconciler error	{"controller": "secret-generator-controller", "controllerGroup": "", "controllerKind": "Secret", "Secret": {"name":"dashboard-oauth-client","namespace":"odh"}, "namespace": "odh", "name": "dashboard-oauth-client", "reconcileID": "067a9ca5-89c8-4353-b0c5-ef241b8946ab", "error": "Incorrect version specified in apply patch. Specified patch version: v1, expected: oauth.openshift.io/v1"}
rename function name
add more comments and debug info message
fix: https://github.com/opendatahub-io/opendatahub-operator/issues/712
ref original from …

fix(oauth-dashboard): apiversion when patch oauthclient + add more debug info

---

components/dashboard/dashboard.go

fix error:
`2023-11-27T08:41:04Z ERROR controllers.DataScienceCluster failed to reconcile dashboard on DataScienceCluster {"instance.Name": "default-dsc", "error": "error deleting secret dashboard-oauth-client in namespace redhat-ods-applications : resource name may not be empty"}`
ref: https://issues.redhat.com/browse/RHODS-12948

fix(secret): do not delete secret if cannot find

---

bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
config/samples/datasciencecluster_v1_datasciencecluster.yaml
config/samples/dscinitialization_v1_dscinitialization.yaml
infrastructure/v1/servicemesh_types.go
pkg/upgrade/upgrade.go

Ref: https://issues.redhat.com/browse/RHOAIENG-126
This PR changes will result in following usecases:
**Self-Managed**
- **New Installs** : Kserve - `Managed` , Modelmesh: `Managed`, Servicemesh(dsci) : `Managed`
- **Upgrade**: Kserve - `same as 2.4`,  Modelmesh: `same as 2.4` , Servicemesh(dsci): `Removed`
Note: If kserve is set to `Managed` in 2.4, users will explicitly need to update `Servicemesh` to `Managed` in DSCI.

Update Defaults for Servicemesh and Kserve

---

components/modelmeshserving/modelmeshserving.go

ref: https://issues.redhat.com/browse/RHOAIENG-293
build 2.4 live: quay.io/wenzhou/rhods-operator-catalog:v2.4.293
build 2.5 live: quay.io/wenzhou/rhods-operator-catalog:v2.5.293 from this PR.
test:
- install 2.4 
only have modelmesh enabled
check resources
- upgrade to 2.5
- 
check if resoruce still there
no prometheus CR
no deployment
no SA
cannot find SerivceMonitor modelmesh-federated-metrics

fix(mm-monitoring): revert the code logic but set to disable as delete

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
components/modelmeshserving/modelmeshserving.go
controllers/dscinitialization/servicemesh_setup.go
get_all_manifests.sh
pkg/deploy/setup.go
pkg/feature/templates/servicemesh/base/control-plane-disable-networkpolicies.patch.tmpl
tests/integration/features/servicemesh_feature_test.go

- change from 2.5 missing on 2.6
- version/branch from components
- generated bundle with rbac
- revert change from ODH: https://github.com/opendatahub-io/opendatahub-operator/pull/809
ref: https://issues.redhat.com/browse/RHOAIENG-1949

fix: couple of changes

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/manifests/bases/rhods-operator.clusterserviceversion.yaml
config/samples/datasciencecluster_v1_datasciencecluster.yaml
docs/DESIGN.md
docs/Dev-Preview.md
pkg/upgrade/upgrade.go

midstream changes https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1517
jira: https://issues.redhat.com/browse/RHOAIENG-2009

update(trustyai): set component by default as Managed as GA in 2.6

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/datasciencecluster/kubebuilder_rbac.go

Rename TrustyAI API group in accordance to https://github.com/trustyai-explainability/trustyai-service-operator/pull/169
- https://issues.redhat.com/browse/RHOAIENG-2020
- https://issues.redhat.com/browse/RHOAIENG-342
- https://github.com/trustyai-explainability/trustyai-service-operator/pull/169

[WIP] RHOAIENG-2020: Rename TrustyAI API group

---

controllers/dscinitialization/servicemesh_setup.go

ref: https://issues.redhat.com/browse/RHOAIENG-2209
offline converstaion: https://redhat-internal.slack.com/archives/C067G701YP6/p1706255091619629
in short: 
we keep the same behavior as in 2.5 for the deletion
we updates the message to user that Removed will not delete SMCP
follow up logic change will be introduced in 2.7

update: to keep SMCP CR even servicemesh state is set to Removed

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/datasciencecluster/kubebuilder_rbac.go

- this is causing MWC CR from kserve did not get cleaned up when kserve is Removed
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/789
ref: https://issues.redhat.com/browse/RHOAIENG-908

sync: from main to rhoai-2.6 (#163)

---

config/monitoring/prometheus/apps/prometheus-configs.yaml

Fixes :  https://issues.redhat.com/browse/RHOAIENG-2189 
Context: 
The service created for the Kserve Controller Manager is badly configured and hence cannot be used to define the scrape config for controller metrics as the existing config results in an invalid scrape target for the SRE prometheus in `redhat-ods-monitoring`. We need to use the controller pod directly as the defined scrape target for these metrics. 
(Thanks @israel-hdez for the solution) 
Changes : 
Changed the scrape config job for Kserve Controller to use the pod directly instead of the service. 
Results: 
The Kserve Controller Manager shows up in the list of Prometheus Targets. 
The previously firing alert is now gone 
Testing Steps: 
- Install the RHOAI 2.6.0 RC1 build using OLM install, specifically as an addon. 
- …

Redefine Kserve Controller Manager scrape config

---

components/trustyai/trustyai.go
config/monitoring/prometheus/apps/prometheus-configs.yaml

as part of https://issues.redhat.com/browse/RHOAIENG-99
we have rules defined in commit https://github.com/red-hat-data-services/rhods-operator/pull/161
but still need the logic in operator to apply such
also tuning these rules from original commit
new:  (live build quay.io/wenzhou/rhods-operator-catalog:v2.6.173) 
update tests:
old: 
test on live build: can confirm config has been applied for trustyai

fix: adding logic to apply trustyai prometheus 

---

bundle/manifests/redhat-ods-operator-controller-manager-metrics-service_v1_service.yaml
config/rbac/auth_proxy_service.yaml

not sure what happened, but this is a mismatch between odh and rhoai
see:
https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/bundle/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
operator should have service on 8080 not on "https"

sync: mismatch between odh and rhoai

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/datasciencecluster/kubebuilder_rbac.go

- this is causing MWC CR from kserve did not get cleaned up when kserve is Removed
backport https://github.com/red-hat-data-services/rhods-operator/pull/174

[backport]: missing get verbs on MWC and secrets

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/manifests/bases/rhods-operator.clusterserviceversion.yaml

ref: https://github.com/red-hat-data-services/rhods-operator/pull/185
see internal converstation: https://redhat-internal.slack.com/archives/C06E98JP45Q/p1707286321280849

[sync]: from main to 2.7 release

---

config/monitoring/base/rhods-servicemonitor.yaml

- it is not in use and was previously imported from modelmesh
https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1707320748074229?thread_ts=1704193152.827009&cid=C03UGJY6Z1A
related to https://issues.redhat.com/browse/RHOAIENG-2479

fix(monitoring): do not create rhods-monitor-federation2

---

config/monitoring/prometheus/apps/prometheus-configs.yaml

* fix(trustyai): prometheus rules for probe
* update(trusty): prometheus to use job instead of instance name for record rules
---------

[backport]: from 2.6 to 2.7  (#173)

---

Makefile
PROJECT
bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
bundle/manifests/redhat-ods-operator-webhook-service_v1_service.yaml
bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
config/default/kustomization.yaml
config/default/manager_webhook_patch.yaml
config/manifests/bases/rhods-operator.clusterserviceversion.yaml
config/webhook/kustomization.yaml
config/webhook/kustomizeconfig.yaml
config/webhook/manifests.yaml
config/webhook/service.yaml
controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
controllers/datasciencecluster/datasciencecluster_controller.go
controllers/dscinitialization/dscinitialization_controller.go
controllers/dscinitialization/dscinitialization_test.go
controllers/webhook/webhook.go
controllers/webhook/webhook_suite_test.go
main.go
tests/e2e/controller_setup_test.go
tests/e2e/dsc_creation_test.go
tests/e2e/helper_test.go

changes:
1. cherrypick commit fb93e5c1b6523c3fd4229b8b533c949ce6d1618e and 46ef53e243928f820a9335a676d4a42c174d3d22 from upstream
2. rename from opendatahub-operator to redhat-ods-operator
live-build: quay.io/wenzhou/rhods-operator-catalog:v2.8.39
-------------
* webhook: add initial skeleton
Originally it was generated with
```operator-sdk create webhook --group datasciencecluster --version v1 --kind DataScienceCluster  --programmatic-validation```
but webhook.Validator interface (like described in the kubebuilder
book[1]) does not work well for the purpose of the webhook due to
needs to access openshift cluster (client.Client) to check existing
instances of DSC.
So, direct implementation of Handler was done inspired by [2] and
odh-notebooks implementation [3].
Move it from api package …

[cherry-pick]: upstream to downstream for webhook

---

config/monitoring/networkpolicy/applications/applications.yaml

- add 9443 to list which is default for component's controller
to lose NWP:  not only limit for monitoring => application, but all others, since we have traffic might be from DSproject to applications as well. 
this can related to the fix kueue made for https://issues.redhat.com/browse/RHOAIENG-3914 to create their own NWP.
we might have other components need 9443 open as well, if we should have operator finally controller NWP instead of component to create their own, then we need to move this into rhoai operator

update(nwp): rhoai open application ns with ingress from all ns

---

components/trustyai/trustyai.go
config/monitoring/prometheus/apps/prometheus-configs.yaml
main.go

We cannot remove manifest references and cleanup logic for 2.8. This is to support upgrade path 2.6 --> 2.8
Ref: https://issues.redhat.com/browse/RHOAIENG-4332

Restore trustyAI manifest references in 2.8

---

pkg/deploy/deploy.go
pkg/upgrade/upgrade.go

ref: https://issues.redhat.com/browse/RHOAIENG-3963
live build: **quay.io/wenzhou/rhods-operator-catalog:v2.10.3963**
will need backport to ODH

update(dashboard): do not set owner on CR

---

pkg/deploy/deploy.go
pkg/upgrade/upgrade.go

* update(dashboard): do not set owner on CR
cherry-pick https://github.com/red-hat-data-services/rhods-operator/pull/224

[cherry-pick]: do not set owner on dashboard CR

---

components/workbenches/workbenches.go
controllers/dscinitialization/utils.go
pkg/upgrade/upgrade.go

ref: https://github.com/opendatahub-io/opendatahub-operator/pull/883
jira https://issues.redhat.com/browse/RHOAIENG-3889
**live build quay.io/wenzhou/rhods-operator-catalog:v2.9.3889-10**
1. test on new installation:
no  label `pod-security.kubernetes.io/enforce `created on redhat-ods-operator namespace
2. test on cleanup:
based on above case, add label `pod-security.kubernetes.io/enforce:baseline`on the redhat-ods-oeprator namespace
then restart operator pod
then check nemspace, label `pod-security.kubernetes.io/enforce` is gone

[cherry-pick]: remove label on operator namespace

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/samples/datasciencecluster_v1_datasciencecluster.yaml
pkg/upgrade/upgrade.go
tests/e2e/helper_test.go

This reverts commit 41a643f460d35f8998e44dbf371634975cdf66af.
due to certain reason, we will need to fix some networkpolicy and auth before we can set this to GA

Revert "feat(DW): prepare CF,ray,kueue for GA (#929)"

---

pkg/gvk/gvk.go
pkg/upgrade/upgrade.go

* pkg/upgrade: abstract resource deletion with Unstructured
For the coming requirement to remove resources not just by their names but a field inside of spec, abstract the existing deleteDeprecatedResources/deleteDeprecatedServiceMonitors to take a resource to delete description as
```
type ResourceSpec struct {
Gvk       schema.GroupVersionKind
Namespace string
Path      []string
Values    []string
}
```
TODO: This patch just adds new functionality without changing the existing calls of deleteDeprecatedResources and
deleteDeprecatedServiceMonitors yet.
The function fetches UnstructuredList by gvk/namespace and uses public unstructured.NestedString() to access the field by path. It should work for ServiceMonitor, where ServiceMonitorList contains list of the pointers, as well.
Ignore …

pkg/upgrade: remove watson-studio dashboard application (#959)

---

pkg/upgrade/upgrade.go

backport https://github.com/red-hat-data-services/rhods-operator/pull/246
ref :https://issues.redhat.com/browse/RHOAIENG-5575

[backport]ray: Cleanup opendatahub Namespace

---

main.go

ref: https://issues.redhat.com/browse/RHOAIENG-6449
this is causing double called in the startup and looks like DSC already exist in the log but actually it was create by the first call
log from Kevin's test
```
I0424 08:47:43.602533       1 request.go:682] Waited for 1.038296111s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/k8s.cni.cncf.io/v1?timeout=32s
2024-04-24T08:47:45Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "0.0.0.0:8080"}
2024-04-24T08:47:45Z	INFO	secret-generator	Adding controller for Secret Generation.
2024-04-24T08:47:45Z	INFO	cert-configmap-generator	Adding controller for Configmap Generation.
starting deletion of Deployment in managed cluster
removing labels on Operator Namespace …
```

fix: remove duplicated call to the upgrade function in main.go

---

controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go

This is part of https://issues.redhat.com/browse/RHOAIENG-5514
Triggers automatic reconcile when namespace is deleted, instead of waiting on eventual reconciliation

Add watch to deleted ns

---

main.go

backport https://github.com/red-hat-data-services/rhods-operator/pull/252

[backport]: fix: remove duplicated call to the upgrade function in main.go

---

pkg/upgrade/upgrade.go

backport https://github.com/red-hat-data-services/rhods-operator/pull/246
ref :https://issues.redhat.com/browse/RHOAIENG-5514

[backport]: 2.9 to main

---

pkg/deploy/deploy.go

ref https://issues.redhat.com/browse/RHOAIENG-6989
it is similar request but on model servering.
we no need to opt on odh-model-controller since it uses the same component name either by kserve or model servering.
As: if we only enabled Kserve but not modelmesh in 2.9.0, we can config odh-model-controller resource already.
local build quay.io/wenzhou/rhods-operator-catalog:v2.9.6989 
manually updated deployment of 
modelmesh-controller to
odh-model-controller to
pods get recreated and stay the same value , not reverted back to original one

feat(modelserving): skip reconcile on deployment resources

---

pkg/deploy/deploy.go

* Fix metadata.managedFields must be nil error in DSC
* Address comments
This commit also updates how we fetch resources from cluster
* Fix getResource function
* addressed comments
* fix linters
* Update resource deletion
Patching resources is not required before deletion. Updated delete function
* Fix linters
(cherry picked from commit f4e66f0972823364b2d8b21ad81c58f07379cf92)

Fix metadata.managedFields must be nil error in DSC (#1018)

---

pkg/cluster/cluster_config.go
pkg/cluster/gvk/gvk.go
pkg/deploy/deploy.go
pkg/upgrade/uninstallation.go

Jira Issue: https://issues.redhat.com/browse/RHOAIENG-7938
GetClusterServiceVersion() may return nil error and nil pointer. On one hand it's ok to check object for nil in not found condition but it's a bit counter intuitive to have err nil when there is acutally "not found"
It caused a problem in GetVersion where this nil condition was not checked.
Refactor it to return the error and handle it properly.
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>
(cherry picked from commit 842550dc209473a79ea7351a6458647dfab2b3c5)

cluster_config: make GetClusterServiceVersion return NotFound error

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/datasciencecluster/kubebuilder_rbac.go
pkg/deploy/deploy.go

Jira Issue: https://issues.redhat.com/browse/RHOAIENG-8393
- since we already have these resource for create, list, delete etc, no harm to add get on them
(cherry picked from commit bd9b83cf95ddb4727575dc7dba2d7cf17dca001a)
fix: when delete resource if no CRD in the cluster (#1044)
(cherry picked from commit c040f77a87521060becf62c2424c39dcb9551458)
deploy: refactor getResource to return NotFound for both cases (#1046)
Avoid returning (nil, nil), convert error if CRD not present to NotFound and handle them in the caller code.
Avoid checking for found == nil but handle only error code.
This is more idiomatic and less error prone.
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>
(cherry picked from …

[rhoai-2.8.3] Fix deploy func refactor

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/manifests/bases/rhods-operator.clusterserviceversion.yaml

we should have these 3 already as GA in 2.10
default DSC set them to Managed, so the value in config is wrong

fix: wrong default value for DW components

---

components/component.go
controllers/dscinitialization/monitoring.go

- reorder and rename map
- add missing kueue into map
- remove ones not existing alerting.rules on KFTO and Kueue

fix: missing entry for kueue and kfto in monitoring

---

tests/e2e/controller_setup_test.go
tests/e2e/dsc_creation_test.go
tests/e2e/dsc_deletion_test.go
tests/e2e/helper_test.go
tests/e2e/odh_manager_test.go

ref: https://issues.redhat.com/browse/RHOAIENG-8550
local test:
```
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_DSCInitialization_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_DataScienceCluster_instance
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Ownerrefrences_exist
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Controller_reconcile
=== RUN   TestOdhOperator/create_Opendatahub_components/e2e-test/Validate_Component_Enabled_field
--- PASS: TestOdhOperator (424.84s)
--- PASS: TestOdhOperator/validate_operator_pod_is_running (31.17s)
--- PASS: TestOdhOperator/validate_operator_pod_is_running/validate_RHOAI_Operator_pod (10.22s)
--- PASS: …
```

test: fix test for rhoai to be used for e2e weekly

---

controllers/dscinitialization/dscinitialization_controller.go
controllers/dscinitialization/monitoring.go

- dashboard is using segment-io's configmap to flip monitoring settings
- upon upgrade, Operator redploy the same configmap to set data to "true"
https://issues.redhat.com/browse/RHOAIENG-1205

[sync]fix: do not redeploy segment-io's if it has been deployed previously

---

pkg/cluster/resources.go

(cherry picked from commit ca3c6e24946faf782fcc779e0013fc118b1d8b94)
missing fix which was on 2.11 but not on main branch which is leading to not on 2.12
https://issues.redhat.com/browse/RHOAIENG-11135
local build quay.io/wenzhou/rhods-operator-catalog:v2.12.0-2

sync: fix for managed cluster upgrade with DSC already exists (#305)

---

config/crd/external/operators.coreos.com_catalogsources.yaml
config/crd/external/operators.coreos.com_operatorconditions.yaml
controllers/dscinitialization/dscinitialization_test.go
controllers/dscinitialization/suite_test.go

- Add DataScienceCluster type to schema for DSCI tests
- Add missing CRDs to run DSCI controller.
- Fix monitoring namespace name in the DSCI test.
make unit-test

Fix unit tests [rhoai-2.8]

---

config/monitoring/prometheus/apps/prometheus-configs.yaml

The dashboard SLO probe alerts reference an incorrect label so when the alert fires the message will have an empty space. This happens because while the metric probe_success contains the instance label.
The alert sums the metric by (name) so it groups away the instance label.
The message should reference the name label not the instance label.
https://issues.redhat.com/browse/RHOAIENG-11746
- Deployed RHOAI with managed monitoring setup.
- Confirm the alert references the wrong label.
- Click show annotations in alertmanager.
- Repeatedly scale down the dashboard pods so the alert fires and confirm the empty space where the label should be in the message.
- Confirm the output of the metric the alert is based on `sum by(name) (probe_success:burnrate5m{name=~"rhods-dashboard"})` outputs the …

fix incorrect label in dashboard SLO probe alerts

---

Dockerfiles/Dockerfile

- in this case, we will get '-rw-rw-r--'
- non-1001 users can run as user for operator pod
(cherry picked from commit 79c6842a7365870b582606b02a24f3a44e11c220)
https://issues.redhat.com/browse/RHOAIENG-10272

[sync] open root group to the same permission as owner

---

components/workbenches/workbenches.go

This should address the [1]. With current code it wasn't possible to override the images used for the notebook controllers via env property, now it should be possible.
(cherry picked from commit 39b7232af026cd6a4c9540aed1a9b07577c2a205)
[1] https://issues.redhat.com/browse/RHOAIENG-11134

Don't restrict the nbc image update to downstream only (#1170)

---

components/dashboard/dashboard.go

- if DSC CR has old format with empty devFlag:{}, it can cause downstream image not replace but run with quay.io one
(cherry picked from commit 1dbe26966fcdddaa5a9d1e7f858ecf958037f7b3)
https://issues.redhat.com/browse/RHOAIENG-12300

[backport] fix: dashboard image not get set in downstream due to devFlags conf (#1224)

---

config/monitoring/prometheus/base/prometheus-rolebinding-viewer.yaml

Openshift 4.16 seems to have made a change to require more permissions for the prometheus instance to federate metrics from the cluster prometheus. Previously view permission for the namespace was all that was required but now permissions to get, create and update `prometheuses/api` is required. These permissions are already encompassed in the `cluster-monitoring-view` role.
https://issues.redhat.com/browse/RHOAIENG-12824
- Confirm that the openshift federation target in prometheus is reporting `down` .
- Change made on local cluster.
- Confirm that the openshift federation target in prometheus is reporting `up`.

add permissions to access prometheuses/api

---

config/monitoring/prometheus/base/prometheus-rolebinding-viewer.yaml

Follow-up to #187 
Need to update it to ClusterRolebinding to fix the issue.
https://issues.redhat.com/browse/RHOAIENG-12824
Catalogsource: quay.io/vhire/opendatahub-operator:rhoai-2.13.1

prometheus: Update to ClusterRoleBinding

---

components/workbenches/workbenches.go
get_all_manifests.sh
pkg/cluster/const.go

- sync to changes in ODH on workbench: to fix the problem of we did not apply correct workbench image before params.env gets updated
- also uplift branch to 2.13 to get new manifests
- refer to https://github.com/opendatahub-io/opendatahub-operator/pull/1226 but since it has the path change, cannot just sync from ODH to rhoai
ref: https://issues.redhat.com/browse/RHOAIENG-12732
- local build with PR: quay.io/wenzhou/rhoai-operator-catalog:v2.14.910-0
result similar to ODH PR
- mock build with passing env for workbenchimages: quay.io/wenzhou/rhoai-operator-catalog:v2.14.910-2
enable workbench
2 CM created + imagestream created: quay.io/modh/.... are used 
see both notebook-controller and kf-notebook-controller have issue to pull image which passed from Operator => expected, params.env is …

fix: workbench deployment + change path for its manifests in build

---

Makefile
PROJECT
bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/default/manager_webhook_patch.yaml
config/monitoring/networkpolicy/operator/operator.yaml
config/webhook/kustomization.yaml
config/webhook/kustomizeconfig.yaml
config/webhook/manifests.yaml
config/webhook/service.yaml
controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
controllers/datasciencecluster/datasciencecluster_controller.go
controllers/dscinitialization/dscinitialization_controller.go
controllers/dscinitialization/dscinitialization_test.go
controllers/webhook/webhook.go
controllers/webhook/webhook_suite_test.go
main.go
tests/e2e/creation_test.go

Jira: https://issues.redhat.com/browse/RHOAIENG-4268
This patch reverts
528801571f00 ("Revert "DSC, DSCI: add validating webhook (#711)"")
Tested:
- deployed catalog
- installed operator
- created DSCI
- created another DSCI with another name, got message that it's prevented

DSC, DSCI: add validating webhook (#711)

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/webhook/manifests.yaml
controllers/webhook/webhook.go
controllers/webhook/webhook_suite_test.go

Backport the patches:
- chore: remove UPDATE from webhook operation list (#1134)
- RHOAIENG-2974: Restrict DSCI deletion before DSC (#1094)
- webhook: refactor with switch and helpers (#1076)

Webhook backport

---

tests/prometheus_unit_tests/codeflare_alerts_unit_tests.yaml

This pr adds support for unit tests for the codeflare alerts
[Jira ticket](https://issues.redhat.com/browse/RHOAIENG-8512)
```
cd tests/prometheus_unit_tests
yq '.data."rhods-dashboard-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > dashboard_alerts.yaml && yq '.data."model-mesh-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_mesh_alerts.yaml && yq '.data."trustyai-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > trustyai_alerts.yaml && yq '.data."odh-model-controller-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_controller_alerts.yaml && yq '.data."workbenches-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yam …
```

RHOAIENG-8512: Implement unit tests for codeflare alerts

---

tests/prometheus_unit_tests/kserve_alerts_unit_tests.yaml
tests/prometheus_unit_tests/training_operator_unit_tests.yaml

[Jira ticket](https://issues.redhat.com/browse/RHOAIENG-8518)
This pr adds support for unit tests for the kserve and kubeflow alerts
```
cd tests/prometheus_unit_tests
yq '.data."rhods-dashboard-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > dashboard_alerts.yaml && yq '.data."model-mesh-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_mesh_alerts.yaml && yq '.data."trustyai-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > trustyai_alerts.yaml && yq '.data."odh-model-controller-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_controller_alerts.yaml && yq '.data."workbenches-alerting.rules"' …
```

RHOAIENG-8518: Implement unit tests for kubeflow training and kserve alerts

---

tests/prometheus_unit_tests/kuberay_alerts_unit_tests.yaml
tests/prometheus_unit_tests/kueue_alerts_unit_tests.yaml
tests/prometheus_unit_tests/workbenches_alerts_unit_tests.yaml

[Jira ticket](https://issues.redhat.com/browse/RHOAIENG-8517)
This pr adds support for unit tests for the kuberay, kueue, kubeflow controller and ODH notebook controller alerts
```
cd tests/prometheus_unit_tests
yq '.data."rhods-dashboard-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > dashboard_alerts.yaml && yq '.data."model-mesh-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_mesh_alerts.yaml && yq '.data."trustyai-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > trustyai_alerts.yaml && yq '.data."odh-model-controller-alerting.rules"' ../../config/monitoring/prometheus/apps/prometheus-configs.yaml > model_controller_alerts.yaml && yq '.data."workbenches-alerting.rules"' …
```

RHOAIENG-8517: Implement unit tests for kuberay, kueue, notebook and kubeflow alerts

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml

Added missing RHOAI-related keywords to the RHOAI operator bundle's CSV, to improve searchability of RHOAI operator
JIRA reference: [RHOAIENG-12537](https://issues.redhat.com/browse/RHOAIENG-12537)
Manually tested on dev OpenShift cluster in the OperatorHub UI
Testing steps:
1. build and push bundle image
2. build and push index/catalog image
3. deploy a CatalogSource that references the index/catalog image into openshift-marketplace namespace
4. search for RHOAI operator in OperatorHub UI using the added keywords

RHOAIENG-12537: Improve Searchability of RHOAI in Operator Catalog

---

controllers/datasciencecluster/datasciencecluster_controller.go
controllers/dscinitialization/dscinitialization_controller.go

- when we do not have e.g dependent operators installed, we should have .status.release info as well
- previous problem is, status update is in the end when reconcile on DSC/DSCI is finished, which can lead to a init value 0.0.0 and dashboard set to 0.0.0 to "About Modal"
https://issues.redhat.com/browse/RHOAIENG-12630

[sync] fix: update DSC/DSCI .status.release not depend on other's reconcile

---

config/monitoring/prometheus/base/prometheus-roles.yaml

Add missing rbac rule to scrape metrics endpoints protected by rbac
See [RHOAIENG-13957](https://issues.redhat.com/browse/RHOAIENG-13957) for more details. 
Tested by adding this rule to the prometheus-scraper role manually in a test QE cluster.

fix: add missing rbac rule to scrape metrics endpoints protected by rbac, fixes RHOAIENG-13957

---

Dockerfiles/Dockerfile.konflux

Adding Dockefile for Konflux transition

---

bundle/manifests/rhods-operator.clusterserviceversion.yaml
config/crd/external/config.openshift.io_authentications.yaml
config/rbac/role.yaml
controllers/dscinitialization/dscinitialization_controller.go
controllers/dscinitialization/dscinitialization_test.go
controllers/dscinitialization/suite_test.go
pkg/cluster/cluster_config.go
pkg/cluster/const.go

- manual cherry-pick from https://github.com/opendatahub-io/opendatahub-operator/pull/1297
https://issues.redhat.com/browse/RHOAIENG-14214

[sync]:feat: Operator disable create usergroup if detect user enable external auth

---

Dockerfiles/Dockerfile.konflux

The UBI8 go-toolset is a single-stream image repository, and therefore won't receive any further updates to the 1.22 tag now that 1.22 is out.
Jira: https://issues.redhat.com/browse/RHOAIENG-16819

Update Dockerfile.konflux to use Go 1.22 builder

---

controllers/components/kserve/kserve_controller.go
pkg/controller/predicates/resources/resources.go
pkg/feature/servicemesh/conditions.go

* It takes more than 10 minutes for kserve-controller to be created during 2.17 installation
* cleanup
(cherry picked from commit 48341ffdc20606a517f65502662d39515716737e)
https://issues.redhat.com/browse/RHOAIENG-18425

[sync] It takes more than 10 minutes for kserve-controller to be created during 2.17 installation (#1564)

---

Dockerfiles/Dockerfile.konflux

https://issues.redhat.com/browse/RHOAIENG-18514

Add Dockerfile.konflux for 2.8

---

pkg/upgrade/upgrade.go

* Remove legacy ModelController deployment on upgrade
When upgrading from version 2.16 to 2.17, the odh-model-controller fails to be provisioned due to the immutability of the deployment's label selectors. In RHOAI ≤ 2.16, the model controller was deployed independently by both kserve and modelmesh, leading to variations in label assignments depending on the deployment order. During a redeployment or upgrade, this error was ignored, and the model controller would eventually be reconciled by the appropriate component.
However, in version 2.17, the model controller is now a defined dependency with its own fixed labels and selectors. This change causes issues during upgrades, as existing deployments cannot be modified accordingly.
* Add comment
* Fix linter findings
(cherry picked from …

[sync]Remove legacy ModelController deployment on upgrade (#1591)

---

prefetched-manifests/kserve/overlays/odh/params.env

chore:	Fixes RHOAIENG-18996, the oauth-proxy sha was incorrectly updated to the same one
than storage-initializer.

[RHOAIENG-18996] -  kserve-storage-initializer and oauth-proxy share the same SHA

---

controllers/components/kserve/kserve_controller.go
controllers/components/kserve/kserve_support.go
pkg/cluster/operator.go
pkg/cluster/resources.go
pkg/cluster/resources_test.go
pkg/utils/test/fakeclient/fakeclient.go

Before this change, these watches don't work properly, and modifying a matching resource doesn't lead to a new reconciliation request being enqueued.
To demonstrate this, once can annotate a matching resource and notice that before this change Kserve reconciliation doesn't happen. With this change, reconciliation occurs as expected.
Co-authored-by: Luca Burgazzoli <lburgazzoli@gmail.com>
(cherry picked from commit e75e4e6a4e9c652a2d22c060d16d0b054e78a705)
this PR includes two ODH changes:
- https://github.com/opendatahub-io/opendatahub-operator/pull/1680 
- https://github.com/opendatahub-io/opendatahub-operator/pull/1678
https://issues.redhat.com/browse/RHOAIENG-20304

[sync]Add missing predicates for Kserve dynamic watches (#1678)

---

config/monitoring/prometheus/apps/prometheus-configs.yaml

https://issues.redhat.com/browse/RHOAIENG-18097
This backports the change from https://github.com/opendatahub-io/opendatahub-operator/pull/1500 (for https://issues.redhat.com/browse/RHOAIENG-18097), to the 2.16 branch.

RHOAIENG-18097: 2.16 backport of RHOAIENG-18095: Deprecation of kube-rbac-proxy

---

.github/workflows/operator-insta-merge.yaml
.github/workflows/operator-processor.yaml

For some reason these were changed on 2.20 in a slightly different way than on main, but the diff is just comments.

Fix conflicting files that are blocking automerge

---

Dockerfiles/Dockerfile.konflux

JIRA: [RHOAIENG-21155](https://issues.redhat.com/browse/RHOAIENG-21155)
This PR updates `Dockerfiles/Dockerfile.konflux` to be compatible with the new kubebuilder `go/v4` project layout.

fix: update Dockerfile.konflux with go/v4 paths

---

pkg/cluster/resources.go

With commit ecdb2dc4, we introduced helper functions to retrieve singleton objects like DataScienceCluster and DSCInitialization. However, under certain yet-to-be-investigated circumstances, retrieving DSCInitialization does not always work reliably. This commit aims to reintroduce the ad-hoc logic for retrieving both DSC and DSCI to address this issue.
Once the root cause will be determined, we should revert back this code and use the shared singleton retreieval logic.
(cherry picked from commit ce054a45430689b625d4da1775311e3cfdbf783b)

[sync] DSCI creation got stuck in operator reconciliation in selfmanaged clusters

---

pkg/controller/conditions/conditions.go
pkg/controller/reconciler/reconciler.go
pkg/controller/reconciler/reconciler_test.go

JIRA: [RHOAIENG-25990](https://issues.redhat.com/browse/RHOAIENG-25990)
Backport of [RHOAIENG-222481](https://issues.redhat.com/browse/RHOAIENG-22481) to 2.19.1.
Will be tested as a part of 2.19.1 testing.
N/A

[rhoai-2.19] Old conditions remain on DSC after upgrade from 2.16

---

controllers/components/kserve/kserve.go
controllers/components/kserve/kserve_controller_actions.go
controllers/components/kserve/kserve_controller_actions_test.go

This is a backport of a65c3fb9e10725fa6211adfb61f046769568f499 to the rhoai-2.19 branch, to address the following issue in 2.19.1:
https://issues.redhat.com/browse/RHOAIENG-24151
This fixes a bug where previously the AuthorizationPolicy and EnvoyFilter resources were only deployed when Authorino was installed, but it was refactored in 2.19 which caused those to be deployed even when Authorino not installed, which is incorrect.
Old code where it only deployed if authorino installed: https://github.com/red-hat-data-services/rhods-operator/blob/rhoai-2.16/components/kserve/servicemesh_setup.go#L46

Only deploy kserve SM resources with Authorino

---

Dockerfiles/Dockerfile.konflux

JIRA: https://issues.redhat.com/browse/RHOAIENG-24688
The UBI8 go-toolset image is single-stream, so it needs to be updated to the new tag to pick up the latest security vulnerability fixes in the Go standard library. The manifest list digest will be kept up-to-date by the konflux/renovate/mintmaker automation, but only to the latest of a particular tag, and since the old tag doesn't receive any updates once the new tag is release, it's necessary to update the tag at least when there are security fixes that need to be picked up.

RHOAIENG-24688: Use go-toolset 1.23 to pick up security fixes

---

build/manifests-config.yaml

This PR updates the pre-fetch script to include the missing configuration needed to copy the llama-stack-k8s-operator manifests into the RHODS operator.

Fix missing llama-stack-k8s-operator manifest copy in pre-fetch script

---

build/manifests-config.yaml

add config to copy manifest for llama-stack-k8s-operator

add config to copy manifest for llama-stack-k8s-operator

---

build/manifests-config.yaml

ref: https://issues.redhat.com/browse/RHOAIENG-29725
Now that kserve images are built in internal konflux and will be published to the catalog, we can fetch the controller manifest precisely using the source git commit

Fetch kserve manifests using git commit

---

pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go

* fix: do not fail during Operator upgrade check error if it is VAPB not have same API version
---------
(cherry picked from commit 033cc3cff2b4b06a4d8ffeb3dd9a7ecd5799799c)
ref: [https://issues.redhat.com/browse/RHOAIENG-31978](https://issues.redhat.com/browse/RHOAIENG-31978)

[sync] fix: do not fail during Operator upgrade check error if it is VAPB not have same API version (#2249)
